# Generated by Django 4.1.3 on 2023-01-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_user_id", models.CharField(max_length=128, unique=True)),
                ("code", models.TextField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blocked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocker", models.CharField(max_length=128)),
                ("blocked", models.CharField(max_length=128)),
            ],
            options={
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
