# Generated by Django 4.1.3 on 2022-11-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("incomingmessagesbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("token", models.TextField(max_length=32, unique=True)),
                (
                    "tg_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_webhooks",
                        to="incomingmessagesbot.telegramchat",
                    ),
                ),
                (
                    "tg_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_webhooks",
                        to="incomingmessagesbot.telegramuser",
                    ),
                ),
            ],
        ),
    ]
